<?php

use Magento\Framework\Escaper;
use Smile\StoreLocator\Block\View\ContactInformation;

/** @var ContactInformation $block */
/** @var Escaper $escaper */
?>
<?php if ($block->hasContactInformation()): ?>
    <div class="contact-info">
        <div class="contact-info-wrapper">
            <h3><?= $escaper->escapeHtml(__('Contact')) ?></h3>
            <table>
                <tbody>
                <?php if ($block->getRetailer()->getContactPhone()): ?>
                    <tr>
                        <td>
                            <span><?= $escaper->escapeHtml(__('Telephone')) ?> : </span>
                            <span itemprop="telephone">
                                <?= $escaper->escapeHtml($block->getRetailer()->getContactPhone()) ?>
                            </span>
                        </td>
                    </tr>
                <?php endif ?>
                <?php if ($block->getRetailer()->getContactFax()): ?>
                    <tr>
                        <td><span><?= $escaper->escapeHtml(__('Fax')) ?> : </span>
                            <span itemprop="faxNumber">
                                <?= $escaper->escapeHtml($block->getRetailer()->getContactFax()) ?>
                            </span>
                        </td>
                    </tr>
                <?php endif ?>
                <?php if ($block->getRetailer()->getContactMail()): ?>
                    <tr>
                        <td>
                            <meta itemprop="email"
                                  content="<?= $escaper->escapeHtml($block->getRetailer()->getContactMail()) ?>"/>
                            <span>
                                <?= $escaper->escapeHtml(__('Mail')) ?> :
                                <a href="mailto:<?= $escaper->escapeHtml($block->getRetailer()->getContactMail()) ?>">
                                    <?= $escaper->escapeHtml($block->getRetailer()->getContactMail()) ?>
                                </a>
                            </span>
                        </td>
                    </tr>
                <?php endif ?>
                </tbody>
                <?php if ($block->showContactForm()): ?>
                    <tfoot>
                        <tr>
                            <td>
                                <span class="contact-form-link">
                                    <a href="<?= $escaper->escapeHtml($block->getContactFormUrl()) ?>">
                                        <?= $escaper->escapeHtml(__('Contact Us')) ?>
                                    </a>
                                </span>
                            </td>
                        </tr>
                    </tfoot>
                <?php endif ?>
            </table>
        </div>
    </div>
<?php endif ?>
