<?php

/** @var \Smile\StoreLocator\Block\View\Map $block */
$retailer = $block->getRetailer();
$image = $block->getImage();
$phone = $block->getPhone();
$mail = $block->getContactMail();
$storeName = $block->getStoreName();
?>

<div id="store-view-map" class="store-view-map clearfix" data-bind="scope: 'store-locator-store-view'" >
    <div data-bind="{ scope: requestChild('geocoder')}">
        <div data-bind=" afterRender: initGeocoder"></div>
    </div>
    <div class="shop-details-wrapper">
        <div class="header">
            <div class="image-wrapper-header">
                <?php if ($image): ?>
                    <img src="<?= $block->escapeHtml($image) ?>"/>
                <?php endif ?>
            </div>
            <div class="store-name">
                <h2><?= $block->escapeHtml($storeName) ?></h2>
            </div>
            <div data-bind="template: storeDetailsWrap"></div>
            <div class="address-info">
                <div class="address">
                   <?= $block->getAddressHtml() ?>
                </div>
                <div itemscope itemprop="address" itemtype="http://schema.org/PostalAddress">
                    <meta itemprop="streetAddress"
                          content="<?= $block->escapeHtml(implode(' ', $block->getAddress()->getStreet())) ?>"/>
                    <meta itemprop="postalCode"
                          content="<?= $block->escapeHtml($block->getAddress()->getPostcode()) ?>"/>
                    <meta itemprop="addressLocality"
                          content="<?= $block->escapeHtml($block->getAddress()->getCity()) ?>"/>
                    <meta itemprop="addressCountry"
                          content="<?= $block->escapeHtml($block->getAddress()->getCountryId()) ?>"/>
                </div>
                <div itemscope itemprop="geo" itemtype="http://schema.org/GeoCoordinates">
                    <meta itemprop="latitude"
                          content="<?= $block->escapeHtml($block->getAddress()->getCoordinates()->getLatitude()) ?>"/>
                    <meta itemprop="longitude"
                          content="<?= $block->escapeHtml($block->getAddress()->getCoordinates()->getLongitude()) ?>"/>
                </div>
            </div>
            <?php if ($phone || $mail): ?>
                <div class="contact-information">
                    <?php if ($phone): ?>
                        <div class="contact-information-phone">
                            <span class="contact-information-label"><?= $block->escapeHtml(__('Tel')) ?>. :</span>
                            <span class="contact-information-value"><?= $block->escapeHtml($phone) ?></span>
                        </div>
                    <?php endif ?>
                    <?php if ($mail): ?>
                        <div class="contact-information-mail">
                            <span class="contact-information-label">E-mail. :</span>
                            <span class="contact-information-value"><?= $block->escapeHtml($mail) ?></span>
                        </div>
                    <?php endif ?>
                </div>
            <?php endif ?>
            <div class="btn-wrapper">
                <div class="directions">
                    <a target="_blank" class="directions-btn"
                       href="<?= $block->escapeHtml($block->getDirectionUrl()) ?>">
                        <span class="directions-btn-icon"></span>
                        <span><?= $block->escapeHtml(__('Go there')) ?></span>
                    </a>
                </div>

                <?= /** @noEscape */$block->getChildHtml('setstorelink') ?>

                <a class= "back-to-result-btn" href="<?= $block->escapeHtml($block->getStoreListUrl()) ?>"
                ><?= $block->escapeHtml(__('Back to results')); ?></a>
            </div>
        </div>
    </div>
    <div class="map" data-bind="afterRender: initMap"></div>
    <div class="banners-wrap" data-bind="template: viewBanersWrapper"></div>
    <div class="nearby-marker-wrapper-container" data-bind="template: nearbyStoreWrapper"></div>
</div>

<script type="text/x-magento-init">
    {"*" : {"Magento_Ui/js/core/app": <?= $block->getJsLayout() ?> }}
</script>
