<?php

use Magento\Framework\Escaper;
use Smile\StoreLocator\Block\View;

/** @var View $block */
/** @var Escaper $escaper */
?>

<div class="set-store-button">
    <a href="#"
       title="<?= $escaper->escapeHtml(__('Choose this store')) ?>"
       class="action-set-store"
       data-post='<?= /* @escapeNotVerified */ $escaper->escapeHtml($block->getSetStorePostJson()) ?>'>
       <span><?= $escaper->escapeHtml(__('Choose this store')) ?></span>
    </a>
</div>
