<?php

/** @var \Smile\StoreLocator\Block\Adminhtml\Retailer\OpeningHours\Container\Renderer $block */

$element = $block->getElement();
$fieldId = $element->getHtmlContainerId() ? ' id="' . $element->getHtmlContainerId() . '"' : '';
$fieldClass = "fieldset-{$element->getId()} {$element->getClass()}";
$fieldClass .= $element->getRequired() ? ' required' : '';
$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" ' . $block->getUiId('form-field', $element->getId());
?>

<div<?= /* @escapeNotVerified */ $fieldAttributes ?>>
    <div class="admin__field-tooltip">
        <p class="note admin__field-tooltip-action">
            <?= /* @escapeNotVerified */ __('Double-click on an opening hour range to delete it.') ?>
        </p>
    </div>
    <?= $block->getInputHtml() ?>
</div>
