<?php

/** @var \Smile\StoreLocator\Block\Adminhtml\Retailer\OpeningHours\Container\Renderer $block */

$element = $block->getElement();
$fieldId = $element->getHtmlContainerId() ? ' id="' . $element->getHtmlContainerId() . '"' : '';
$fieldClass = "fieldset-{$element->getId()} {$element->getClass()}";
$fieldClass .= $element->getRequired() ? ' required' : '';
$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" ' . $block->getUiId('form-field', $element->getId());
?>

<?php // @codingStandardsIgnoreStart - if escaped, will not work ?>
<div<?= /* @escapeNotVerified */ $fieldAttributes ?>>
<?php // @codingStandardsIgnoreEnd ?>
    <div class="admin__field-tooltip">
        <p class="note admin__field-tooltip-action">
            <?= $block->escapeHtml(__('Double-click on an opening hour range to delete it.')) ?>
        </p>
    </div>
    <?= $block->getInputHtml() ?>
</div>
