<?php

/** @var \Smile\StoreLocator\Block\Adminhtml\Retailer\OpeningHours\Element\Renderer $block */

$element = $block->getElement();
$fieldId = $element->getHtmlContainerId() ? ' id="' . $element->getHtmlContainerId() . '"' : '';
$fieldClass = "field admin__field field-{$element->getId()} {$element->getClass()}";
$fieldClass .= $element->getRequired() ? ' required' : '';
$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" ' . $block->getUiId('form-field', $element->getId());
?>
<?php // @codingStandardsIgnoreStart - if escaped, will not work ?>
<div<?= /* @escapeNotVerified */ $fieldAttributes ?>>
<?php // @codingStandardsIgnoreEnd ?>
    <?= $element->getLabelHtml() ?><span class="opening-hours-day" id="<?= $block->getHtmlId() ?>-label"></span>
    <?php $inputId = 'opening_hours_field_' . $block->getHtmlId() ?>
    <div id ="<?= $block->escapeHtml($inputId) ?>" class="opening-hours-container">
        <div class="opening-hours-indicator"></div>
        <div class="opening-hours-rangebar"></div>
        <?= $block->getInputHtml() ?>
    </div>
</div>

<script>

    require(["jquery", "openingHours", "moment"],
        function($, openingHours, moment) {
            /**
             * This component is the main timepicker for opening hours
             */
            $("#<?= $block->escapeHtml($inputId) ?> .opening-hours-rangebar").openingHours({
                values: $("#<?= $block->getHtmlId() ?>").val(),
                summary: $("#<?= $block->getHtmlId() ?>-label"),
                updateSummary: true,
                input : $("#<?= $block->getHtmlId() ?>")
            });

            /**
             * This component is a read-only one, made to display the time indicator
             */
            $("#<?= $block->escapeHtml($inputId) ?> .opening-hours-indicator").openingHours({
                values: [
                    [moment().startOf("day").format("LLLL")],
                    [moment().startOf("day").add(3, "hours").format("LLLL")],
                    [moment().startOf("day").add(6, "hours").format("LLLL")],
                    [moment().startOf("day").add(9, "hours").format("LLLL")],
                    [moment().startOf("day").add(12, "hours").format("LLLL")],
                    [moment().startOf("day").add(15, "hours").format("LLLL")],
                    [moment().startOf("day").add(18, "hours").format("LLLL")],
                    [moment().startOf("day").add(21, "hours").format("LLLL")],
                    [moment().startOf("day").add(24, "hours").format("LLLL")],
                ],
                label: function(a){return JSON.stringify(a[0])},
                readonly: true
            });
        }
    );
</script>
